from __future__ import annotations
from dataclasses import dataclass, field
from typing import Any
from tgchatbot.domain.models import ConversationMessage, MessageRole, PartKind
from tgchatbot.domain.timestamps import format_timestamp
from tgchatbot.domain.identities import format_actor_labels


def matching_tool_result(call_message: ConversationMessage, result_message: ConversationMessage) -> bool:
    call_meta, result_meta = call_message.metadata, result_message.metadata
    if (call_message.role != MessageRole.TOOL or call_meta.get('tool_phase') != 'call'
            or result_message.role != MessageRole.TOOL or result_meta.get('tool_phase') != 'result'):
        return False
    call_payload, result_payload = call_meta.get('tool_payload') or {}, result_meta.get('tool_payload') or {}
    call_id, result_id = str(call_payload.get('call_id') or ''), str(result_payload.get('call_id') or '')
    if call_id and result_id:
        return call_id == result_id
    return (call_message.name or '') == (result_message.name or '')


def is_auto_note_message(message: ConversationMessage) -> bool:
    return message.metadata.get('synthetic_role') == 'auto_user_note' or any(
        (part.origin or '') == 'auto_note' for part in message.parts)

@dataclass(slots=True)
class StoredConversationMessage:
    db_id: int
    message: ConversationMessage
    estimated_tokens: int
    created_at: int | None = None
    context_version: int = field(default=0, compare=False, repr=False)
    @property
    def image_count(self) -> int:
        return sum(1 for part in self.message.parts if part.kind == PartKind.IMAGE
            and (part.data_b64 or part.preview_ref))

@dataclass(slots=True)
class MemoryBlock:
    block_id: int
    sequence_no: int
    summary_text: str
    estimated_tokens: int
    source_message_count: int
    start_message_id: int | None = None
    end_message_id: int | None = None
    level: int = 1
    kind: str = "episode"
    lifecycle: str = "sealed"
    source_kind: str = "raw"
    parent_block_ids: tuple[int, ...] = ()
    topic_labels: tuple[str, ...] = ()
    actor_labels: tuple[str, ...] = ()
    actor_identities: tuple[dict[str, Any], ...] | None = None
    time_start: str | None = None
    time_end: str | None = None
    retained_raw_excerpt_count: int = 0
    validator_status: str | None = None
    validator_score: float | None = None
    structured_data: dict[str, Any] = field(default_factory=dict)
    presentation_version: int = 1
    compaction_version: int = field(default=0, compare=False, repr=False)
    def render_as_message(self, *, timezone: str | None = None) -> ConversationMessage:
        start = format_timestamp(self.time_start, timezone)
        end = format_timestamp(self.time_end, timezone)
        scope_bits: list[str] = []
        scope = self.structured_data.get('scope') or {
            'toolspan': 'Tool-heavy interaction span', 'episode': 'Episode summary',
        }.get(self.kind, 'Digest summary')
        scope_prefix = f'## Scope\n- {scope}\n'
        # Deduplicate only the renderer-owned leading scope, never matching
        # lines in model prose, retained quotations or a later section.
        scope_lines = (self.summary_text[len(scope_prefix):].split('\n\n', 1)[0].splitlines()
            if self.presentation_version >= 2 and self.summary_text.startswith(scope_prefix) else [])
        rendered_span = f'{start} .. {end}' if start and end and start != end else start or end
        duplicate_time = any(
            line == f'- Time span: {rendered_span}' or line == '- Time span: ' + str(
                f'{self.time_start} .. {self.time_end}' if self.time_start and self.time_end and self.time_start != self.time_end
                else self.time_start or self.time_end)
            for line in scope_lines)
        if (start or end) and not duplicate_time:
            if start and end and start != end:
                scope_bits.append(f"time={start}..{end}")
            else:
                scope_bits.append(f"time={start or end}")
        if self.actor_labels and '- Participants: ' + format_actor_labels(self.actor_labels, self.actor_identities) not in scope_lines:
            labels = self.actor_labels if self.presentation_version >= 2 else self.actor_labels[:4]
            scope_bits.append("actors=" + format_actor_labels(labels, self.actor_identities))
        if self.topic_labels and '- Topics: ' + ', '.join(self.topic_labels) not in scope_lines:
            labels = self.topic_labels if self.presentation_version >= 2 else self.topic_labels[:4]
            scope_bits.append("topics=" + ", ".join(labels))
        header = f"[Memory {self.kind} block L{self.level} #{self.sequence_no}; covers {self.source_message_count} earlier messages"
        if scope_bits:
            header += "; " + "; ".join(scope_bits)
        header += "]"
        summary = self.summary_text
        if start or end:
            # This line is generated by the block renderer from structured
            # bounds. Original quotations and model-written prose stay intact.
            stored_span = (f'{self.time_start} .. {self.time_end}'
                if self.time_start and self.time_end and self.time_start != self.time_end
                else self.time_start or self.time_end)
            shown_span = f'{start} .. {end}' if start and end and start != end else start or end
            prefix = f'## Scope\n- {scope}\n- Time span: '
            stored_header = prefix + str(stored_span)
            if summary == stored_header or summary.startswith(stored_header + '\n'):
                summary = prefix + str(shown_span) + summary[len(stored_header):]
        return ConversationMessage.assistant_text(header + "\n" + summary)

@dataclass(slots=True)
class LiveConversationState:
    session_id: str
    blocks: list[MemoryBlock] = field(default_factory=list)
    raw_messages: list[StoredConversationMessage] = field(default_factory=list)
    estimated_tokens: int = 0
    estimated_images: int = 0
    last_message_id: int = 0
    loaded: bool = False
    cache_revision: int = 0
    database_version: int = -1
    provider_history_cache: list[ConversationMessage] = field(default_factory=list)
    provider_history_cache_key: tuple[str, str, str, tuple[int, ...], int] | None = None
    provider_history_dirty: bool = True

    @staticmethod
    def active_participant_ids(messages: list[ConversationMessage],
                               trigger: ConversationMessage | None = None) -> list[str]:
        """Prioritize the trigger, then supplied original speakers and direct replies."""
        participants: dict[str, None] = {}
        reply_participants: dict[str, None] = {}

        def known_actor(metadata: dict[str, Any]) -> str | None:
            actor = metadata.get('actor_id')
            if metadata.get('actor_kind') in {'bot', 'unknown'} or not isinstance(actor, str):
                return None
            actor = actor.strip()
            return actor if actor and actor not in {'unknown', 'agent'} else None

        def collect(message: ConversationMessage) -> None:
            metadata = message.metadata
            if message.role != MessageRole.USER or metadata.get('synthetic_role'):
                return
            actor = known_actor(metadata)
            if actor is not None:
                participants.setdefault(actor, None)
            reply_actor = metadata.get('reply_to_actor')
            source_chat = metadata.get('source_chat_id')
            if (isinstance(reply_actor, dict) and metadata.get('reply_to_source_id') is not None
                    and source_chat not in (None, '', 'unknown')
                    and str(metadata.get('reply_to_source_chat_id')) == str(source_chat)):
                actor = known_actor(reply_actor)
                if actor is not None:
                    reply_participants.setdefault(actor, None)

        if trigger is not None:
            collect(trigger)
        for message in messages:
            collect(message)
        for actor in reply_participants:
            participants.setdefault(actor, None)
        return list(participants)

    def rebuild_estimate(self) -> int:
        self.cache_revision += 1
        self.estimated_tokens = sum(block.estimated_tokens for block in self.blocks) + sum(item.estimated_tokens for item in self.raw_messages)
        self.estimated_images = sum(item.image_count for item in self.raw_messages)
        self.last_message_id = max(max((item.db_id for item in self.raw_messages), default=0),
            max((block.end_message_id or 0 for block in self.blocks), default=0))
        self.provider_history_dirty = True
        self.provider_history_cache_key = None
        return self.estimated_tokens


@dataclass(slots=True)
class CompactionWorkingSet(LiveConversationState):
    """A bounded database projection for maintenance, never a live cache entry."""
    through_message_id: int = 0
    more_raw: bool = False
    more_blocks: bool = False


@dataclass(frozen=True, slots=True)
class ImageRetirement:
    removed_images: int
    compaction_version: int | None = None
