from __future__ import annotations

import unittest
from pathlib import Path

from tgchatbot.stickers.catalog import (
    StickerIndexEntry,
    _caption_evidence_bonus,
    _compatibility_adjustment,
    _fuse_scores,
    _keyword_bonus,
)
from tgchatbot.stickers.plan import StickerRetrievalPlan
from tgchatbot.stickers.schema import STICKER_RESPONSE_SCHEMA, compose_sticker_semantic_text


def make_entry(
    *,
    sticker_id: str,
    caption_mode: str,
    summary: str,
    selection_notes: str,
    caption_meaning_en: str,
    caption_meaning_zh: str,
    caption_semantic_text: str,
    sticker_semantic_text: str,
    source_overlay_text: str,
    caption_card: dict,
    subtle_cue_card: dict,
    sticker_card: dict,
    semantic_signature: str,
) -> StickerIndexEntry:
    return StickerIndexEntry(
        sticker_id=sticker_id,
        relative_path=f'{sticker_id}.webp',
        absolute_path=Path(f'/tmp/{sticker_id}.webp'),
        source_format='webp',
        source_pack_id='pack_a',
        source_pack_hash=1,
        summary=summary,
        preview_text=summary,
        selection_notes=selection_notes,
        emoji=None,
        caption_mode=caption_mode,
        source_overlay_text=source_overlay_text,
        source_overlay_text_normalized=source_overlay_text,
        caption_meaning_en=caption_meaning_en,
        caption_meaning_zh=caption_meaning_zh,
        source_overlay_languages=['chinese'] if source_overlay_text else [],
        source_ocr_confidence=0.98,
        source_ocr_confidence_bucket=4,
        caption_dominance_score=4 if source_overlay_text else 0,
        caption_semantic_text=caption_semantic_text,
        sticker_semantic_text=sticker_semantic_text,
        style_text='flat anime meme sticker ; soft pastel',
        style_cluster='style_a',
        style_cluster_id=1,
        semantic_signature=semantic_signature,
        caption_card=caption_card,
        subtle_cue_card=subtle_cue_card,
        sticker_card=sticker_card,
        style_card={
            'style_rendering_type': 'flat anime meme sticker',
            'line_weight': 'medium',
            'style_palette_family': 'soft pastel',
            'meme_intensity': 'high',
            'style_text_prominence': 'high' if source_overlay_text else 'low',
            'style_character_family': 'round chibi cat',
        },
        harshness_level=int(caption_card.get('harshness_level', 1)),
        intimacy_level=int(caption_card.get('intimacy_level', 1)),
        meme_dependence_level=int(caption_card.get('meme_dependence_level', 1)),
        animated=False,
        metadata_json='{}',
        parsed_metadata={},
    )


class StickerSemanticTests(unittest.TestCase):
    def test_schema_exposes_visual_pragmatics_section(self) -> None:
        self.assertIn('subtle_cue_card', STICKER_RESPONSE_SCHEMA['properties'])
        subtle = STICKER_RESPONSE_SCHEMA['properties']['subtle_cue_card']
        self.assertIn('visual_reply_force', subtle['properties'])
        self.assertIn('visual_irony_strength', subtle['properties'])
        self.assertIn('visual_emotional_valence', subtle['properties'])

    def test_textless_visual_semantics_flow_into_sticker_text(self) -> None:
        semantics = {
            'caption_card': {
                'caption_mode': 'visual_dominant',
                'caption_literal_meaning': '',
                'caption_pragmatic_meaning': '',
                'caption_discourse_role': '',
                'caption_target_direction': '',
                'caption_social_stance': '',
                'caption_reply_force': '',
                'caption_emotional_valence': '',
                'caption_irony_strength': '',
                'caption_relationship_fit': '',
                'caption_conversation_role': '',
                'caption_use_when': '',
                'caption_avoid_when': '',
                'caption_close_aliases': '',
                'caption_meaning_en': '',
                'caption_meaning_zh': '',
                'harshness_level': 1,
                'intimacy_level': 1,
                'meme_dependence_level': 1,
            },
            'subtle_cue_card': {
                'dominant_signal': 'flat side-eye',
                'micro_expression': 'tiny smirk',
                'eye_signal': 'dry disbelief',
                'mouth_signal': 'tight amused line',
                'pose_signal': 'still unimpressed pose',
                'head_signal': 'slight tilt',
                'hand_signal': 'none',
                'color_signal': 'cool muted palette',
                'composition_signal': 'tight crop',
                'motion_signal': 'minimal motion',
                'visual_social_stance': 'dryly dismissive',
                'visual_reply_force': 'firm rejection',
                'visual_emotional_valence': 'negative',
                'visual_irony_strength': 'high',
                'visual_relationship_fit': 'friends',
                'visual_conversation_role': 'silent side-eye reaction',
                'visual_use_when': 'When a look says enough.',
                'visual_avoid_when': 'When sincere comfort is needed.',
            },
            'sticker_card': {
                'sticker_reaction_type': 'silent side-eye disbelief',
                'fused_pragmatic_meaning': 'Dry ironic rejection without words.',
                'sticker_visual_emotion': 'dry disbelief',
                'sticker_humor_style': 'deadpan irony',
                'sticker_delivery_style': 'minimal expression with strong subtext',
                'sticker_subject_type': 'cat face',
                'sticker_art_softening_strength': 'low',
                'sticker_general_usefulness': 'useful for wordless disbelief',
                'sticker_reply_force': 'firm rejection',
                'sticker_emotional_valence': 'negative',
                'sticker_irony_strength': 'high',
                'sticker_relationship_fit': 'friends',
                'sticker_conversation_role': 'silent side-eye reaction',
                'sticker_use_when': 'When a look says enough.',
                'sticker_avoid_when': 'When warmth is needed.',
            },
            'style_card': {
                'style_rendering_type': 'flat meme sticker',
                'line_weight': 'medium',
                'style_palette_family': 'cool muted',
                'meme_intensity': 'medium',
                'style_text_prominence': 'low',
                'style_character_family': 'cat',
            },
        }
        sticker_text = compose_sticker_semantic_text(semantics)
        self.assertIn('dry disbelief', sticker_text)
        self.assertIn('firm rejection', sticker_text)
        self.assertIn('silent side-eye reaction', sticker_text)

    def test_wuyu_style_caption_scores_above_neutral_speechless(self) -> None:
        plan = StickerRetrievalPlan.from_payload(
            {
                'intent_core': 'fed-up dismissive rebuttal',
                'secondary_goals': ['annoyed disbelief', 'can\'t even', 'shut the argument down'],
                'text_priority': 'require',
                'forbid': ['neutral speechless'],
                'candidate_budget': 3,
            }
        )
        wuyu = make_entry(
            sticker_id='wuyu',
            caption_mode='caption_dominant',
            summary='Fed-up dismissive rebuttal with cute shell.',
            selection_notes='Use for exasperated dismissal or annoyed rebuttal; avoid when warmth is needed.',
            caption_meaning_en="I can't even; I'm done talking because this is ridiculous.",
            caption_meaning_zh='无语，跟你说不下去',
            caption_semantic_text='dismissive rebuttal ; annoyed disbelief ; strong shutdown ; exasperated',
            sticker_semantic_text='cute shell around sharp rebuttal ; firm rejection',
            source_overlay_text='无语, 跟你说不下去',
            caption_card={
                'caption_mode': 'caption_dominant',
                'caption_literal_meaning': 'Speechless; cannot keep talking.',
                'caption_pragmatic_meaning': 'Exasperated dismissive rebuttal that shuts the exchange down.',
                'caption_discourse_role': 'rebuttal',
                'caption_target_direction': 'other_person',
                'caption_social_stance': 'dismissive, annoyed, fed up',
                'caption_reply_force': 'strong shutdown',
                'caption_emotional_valence': 'negative',
                'caption_irony_strength': 'medium',
                'caption_relationship_fit': 'friends, chaotic group chat',
                'caption_conversation_role': 'turn-ending clapback',
                'caption_use_when': 'When a ridiculous take makes you want to stop arguing.',
                'caption_avoid_when': 'When comfort or diplomacy is required.',
                'caption_close_aliases': "I can't even; I'm done arguing.",
                'caption_meaning_en': "I can't even; I'm done talking because this is ridiculous.",
                'caption_meaning_zh': '受不了了，不想再和你争了',
                'harshness_level': 3,
                'intimacy_level': 2,
                'meme_dependence_level': 2,
            },
            subtle_cue_card={
                'dominant_signal': 'flat glare',
                'micro_expression': 'micro-scowl',
                'eye_signal': 'annoyed disbelief',
                'mouth_signal': 'tiny grimace',
                'pose_signal': 'rigid fed-up pose',
                'head_signal': 'dismissive tilt',
                'hand_signal': 'none',
                'color_signal': 'muted irritation',
                'composition_signal': 'text-forward crop',
                'motion_signal': 'stillness',
                'visual_social_stance': 'unimpressed',
                'visual_reply_force': 'firm rejection',
                'visual_emotional_valence': 'negative',
                'visual_irony_strength': 'medium',
                'visual_relationship_fit': 'friends',
                'visual_conversation_role': 'reaction shot',
                'visual_use_when': 'When annoyed disbelief should show on the face too.',
                'visual_avoid_when': 'When you need to look warm.',
            },
            sticker_card={
                'sticker_reaction_type': 'dismissive disagreement',
                'fused_pragmatic_meaning': 'Cute-looking but actually fed-up rebuttal that ends the exchange.',
                'sticker_visual_emotion': 'annoyed deadpan',
                'sticker_humor_style': 'meme sarcasm',
                'sticker_delivery_style': 'cute shell around a stronger shutdown',
                'sticker_subject_type': 'chibi cat',
                'sticker_art_softening_strength': 'softens slightly but does not neutralize the rebuttal',
                'sticker_general_usefulness': 'useful for dismissive disagreement',
                'sticker_reply_force': 'strong rebuttal',
                'sticker_emotional_valence': 'negative',
                'sticker_irony_strength': 'medium_high',
                'sticker_relationship_fit': 'friends',
                'sticker_conversation_role': 'turn-ending reaction shot',
                'sticker_use_when': 'When you want to shut down a goofy argument.',
                'sticker_avoid_when': 'When diplomacy is needed.',
            },
            semantic_signature='sig_wuyu',
        )
        neutral = make_entry(
            sticker_id='neutral',
            caption_mode='caption_dominant',
            summary='Neutral speechless reaction.',
            selection_notes='Use for quiet surprise, not for dismissal.',
            caption_meaning_en='Speechless and quietly stunned.',
            caption_meaning_zh='说不出话',
            caption_semantic_text='neutral speechless ; stunned ; quiet surprise',
            sticker_semantic_text='gentle surprise reaction',
            source_overlay_text='无语',
            caption_card={
                'caption_mode': 'caption_dominant',
                'caption_literal_meaning': 'Speechless.',
                'caption_pragmatic_meaning': 'Neutral speechlessness.',
                'caption_discourse_role': 'reaction',
                'caption_target_direction': 'situation',
                'caption_social_stance': 'neutral, stunned',
                'caption_reply_force': 'low',
                'caption_emotional_valence': 'neutral',
                'caption_irony_strength': 'low',
                'caption_relationship_fit': 'anyone',
                'caption_conversation_role': 'quiet reaction',
                'caption_use_when': 'When words fail for neutral surprise.',
                'caption_avoid_when': 'When you need a rebuttal.',
                'caption_close_aliases': 'speechless, stunned',
                'caption_meaning_en': 'Speechless and quietly stunned.',
                'caption_meaning_zh': '说不出话',
                'harshness_level': 0,
                'intimacy_level': 0,
                'meme_dependence_level': 0,
            },
            subtle_cue_card={
                'dominant_signal': 'blank look',
                'micro_expression': 'none',
                'eye_signal': 'wide eyes',
                'mouth_signal': 'small open mouth',
                'pose_signal': 'still',
                'head_signal': 'none',
                'hand_signal': 'none',
                'color_signal': 'neutral palette',
                'composition_signal': 'centered',
                'motion_signal': 'none',
                'visual_social_stance': 'neutral',
                'visual_reply_force': 'low',
                'visual_emotional_valence': 'neutral',
                'visual_irony_strength': 'low',
                'visual_relationship_fit': 'anyone',
                'visual_conversation_role': 'quiet reaction',
                'visual_use_when': 'When softly surprised.',
                'visual_avoid_when': 'When you need dismissal.',
            },
            sticker_card={
                'sticker_reaction_type': 'speechless surprise',
                'fused_pragmatic_meaning': 'Quietly stunned reaction.',
                'sticker_visual_emotion': 'surprised',
                'sticker_humor_style': 'none',
                'sticker_delivery_style': 'soft neutral reaction',
                'sticker_subject_type': 'chibi cat',
                'sticker_art_softening_strength': 'high',
                'sticker_general_usefulness': 'general surprise',
                'sticker_reply_force': 'low',
                'sticker_emotional_valence': 'neutral',
                'sticker_irony_strength': 'low',
                'sticker_relationship_fit': 'anyone',
                'sticker_conversation_role': 'quiet reaction',
                'sticker_use_when': 'When softly stunned.',
                'sticker_avoid_when': 'When you need a rebuttal.',
            },
            semantic_signature='sig_neutral',
        )

        def total_score(entry: StickerIndexEntry) -> float:
            score = _fuse_scores(
                caption_lexical=1.0,
                sticker_lexical=1.0,
                caption_semantic=1.0,
                sticker_semantic=1.0,
                text_priority=plan.text_priority,
                caption_mode=entry.caption_mode,
            )
            score += _caption_evidence_bonus(entry=entry, query_text=plan.caption_query_text(), text_priority=plan.text_priority)
            keyword_bonus, _ = _keyword_bonus(entry, plan.request_terms())
            score += keyword_bonus
            score += _compatibility_adjustment(entry=entry, plan=plan)
            return score

        self.assertGreater(total_score(wuyu), total_score(neutral))

    def test_visual_only_ironic_sticker_beats_blank_candidate(self) -> None:
        plan = StickerRetrievalPlan.from_payload(
            {
                'intent_core': 'dry ironic side-eye disbelief',
                'secondary_goals': ['textless reaction', 'firm rejection'],
                'text_priority': 'ignore',
                'candidate_budget': 3,
            }
        )
        visual = make_entry(
            sticker_id='visual',
            caption_mode='visual_dominant',
            summary='Dry ironic side-eye.',
            selection_notes='Use when a wordless look should reject a silly take.',
            caption_meaning_en='',
            caption_meaning_zh='',
            caption_semantic_text='',
            sticker_semantic_text='dry ironic side-eye disbelief ; firm rejection ; deadpan reaction',
            source_overlay_text='',
            caption_card={
                'caption_mode': 'visual_dominant',
                'caption_literal_meaning': '',
                'caption_pragmatic_meaning': '',
                'caption_discourse_role': '',
                'caption_target_direction': '',
                'caption_social_stance': '',
                'caption_reply_force': '',
                'caption_emotional_valence': '',
                'caption_irony_strength': '',
                'caption_relationship_fit': '',
                'caption_conversation_role': '',
                'caption_use_when': '',
                'caption_avoid_when': '',
                'caption_close_aliases': '',
                'caption_meaning_en': '',
                'caption_meaning_zh': '',
                'harshness_level': 1,
                'intimacy_level': 1,
                'meme_dependence_level': 1,
            },
            subtle_cue_card={
                'dominant_signal': 'flat side-eye',
                'micro_expression': 'tiny smirk',
                'eye_signal': 'dry disbelief',
                'mouth_signal': 'tight amused line',
                'pose_signal': 'still unimpressed pose',
                'head_signal': 'slight tilt',
                'hand_signal': 'none',
                'color_signal': 'cool muted palette',
                'composition_signal': 'tight crop',
                'motion_signal': 'minimal motion',
                'visual_social_stance': 'dryly dismissive',
                'visual_reply_force': 'firm rejection',
                'visual_emotional_valence': 'negative',
                'visual_irony_strength': 'high',
                'visual_relationship_fit': 'friends',
                'visual_conversation_role': 'silent side-eye reaction',
                'visual_use_when': 'When a look says enough.',
                'visual_avoid_when': 'When sincere comfort is needed.',
            },
            sticker_card={
                'sticker_reaction_type': 'silent side-eye disbelief',
                'fused_pragmatic_meaning': 'Dry ironic rejection without words.',
                'sticker_visual_emotion': 'dry disbelief',
                'sticker_humor_style': 'deadpan irony',
                'sticker_delivery_style': 'minimal expression with strong subtext',
                'sticker_subject_type': 'cat face',
                'sticker_art_softening_strength': 'low',
                'sticker_general_usefulness': 'useful for wordless disbelief',
                'sticker_reply_force': 'firm rejection',
                'sticker_emotional_valence': 'negative',
                'sticker_irony_strength': 'high',
                'sticker_relationship_fit': 'friends',
                'sticker_conversation_role': 'silent side-eye reaction',
                'sticker_use_when': 'When a look says enough.',
                'sticker_avoid_when': 'When warmth is needed.',
            },
            semantic_signature='sig_visual',
        )
        blank = make_entry(
            sticker_id='blank',
            caption_mode='visual_dominant',
            summary='Generic cute face.',
            selection_notes='Generic cute reaction.',
            caption_meaning_en='',
            caption_meaning_zh='',
            caption_semantic_text='',
            sticker_semantic_text='cute generic reaction',
            source_overlay_text='',
            caption_card={
                'caption_mode': 'visual_dominant',
                'caption_literal_meaning': '',
                'caption_pragmatic_meaning': '',
                'caption_discourse_role': '',
                'caption_target_direction': '',
                'caption_social_stance': '',
                'caption_reply_force': '',
                'caption_emotional_valence': '',
                'caption_irony_strength': '',
                'caption_relationship_fit': '',
                'caption_conversation_role': '',
                'caption_use_when': '',
                'caption_avoid_when': '',
                'caption_close_aliases': '',
                'caption_meaning_en': '',
                'caption_meaning_zh': '',
                'harshness_level': 0,
                'intimacy_level': 0,
                'meme_dependence_level': 0,
            },
            subtle_cue_card={
                'dominant_signal': 'cute face',
                'micro_expression': 'none',
                'eye_signal': 'round eyes',
                'mouth_signal': 'small smile',
                'pose_signal': 'still',
                'head_signal': 'none',
                'hand_signal': 'none',
                'color_signal': 'soft pastel',
                'composition_signal': 'centered',
                'motion_signal': 'none',
                'visual_social_stance': 'neutral',
                'visual_reply_force': 'low',
                'visual_emotional_valence': 'positive',
                'visual_irony_strength': 'low',
                'visual_relationship_fit': 'anyone',
                'visual_conversation_role': 'generic reaction',
                'visual_use_when': 'Any mild reaction.',
                'visual_avoid_when': 'When you need a strong stance.',
            },
            sticker_card={
                'sticker_reaction_type': 'generic cute reaction',
                'fused_pragmatic_meaning': 'Mild generic cute response.',
                'sticker_visual_emotion': 'cute',
                'sticker_humor_style': 'none',
                'sticker_delivery_style': 'soft generic expression',
                'sticker_subject_type': 'cat face',
                'sticker_art_softening_strength': 'high',
                'sticker_general_usefulness': 'general purpose',
                'sticker_reply_force': 'low',
                'sticker_emotional_valence': 'positive',
                'sticker_irony_strength': 'low',
                'sticker_relationship_fit': 'anyone',
                'sticker_conversation_role': 'generic reaction',
                'sticker_use_when': 'Any mild reaction.',
                'sticker_avoid_when': 'When you need a firm stance.',
            },
            semantic_signature='sig_blank',
        )

        def total_score(entry: StickerIndexEntry) -> float:
            score = _fuse_scores(
                caption_lexical=0.2,
                sticker_lexical=0.9,
                caption_semantic=0.2,
                sticker_semantic=1.0,
                text_priority=plan.text_priority,
                caption_mode=entry.caption_mode,
            )
            score += _caption_evidence_bonus(entry=entry, query_text=plan.caption_query_text(), text_priority=plan.text_priority)
            keyword_bonus, _ = _keyword_bonus(entry, plan.request_terms())
            score += keyword_bonus
            score += _compatibility_adjustment(entry=entry, plan=plan)
            return score

        self.assertGreater(total_score(visual), total_score(blank))


if __name__ == '__main__':
    unittest.main()
